version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: minha_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      DATABASE_URL: "postgresql://dbadmin:dbPassword1108@database-1.cf64eqcyyvd7.us-east-2.rds.amazonaws.com:5432/mydatabase"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

networks:
  default:
    driver: bridge
